# Hello Django

## 27.9.2024

## a) Esimerkkiohjelma Djangolla

> Klo 18:52, tuotantoympäristön asennuksen aloitus

Aloitin tehtävien teon käynnistämällä virtuaalikoneeni ja ajamalla siellä terminaalissa tutun komennon `sudo apt-get update`. Päivitysten jälkeen otin yhteyden virtuaalipalvelimeeni komennolla `ssh erikak@165.232.86.216`, ja ajoin myös siellä päivityskomennon.

Lähdin etenemään Tero Karvisen ohjeen mukaan (lähde: Tero Karvinen, https://terokarvinen.com/2022/django-instant-crm-tutorial/), ja ensimmäisenä asensin virtuaalipalvelimelleni virtualenvin, joka on siis työkalu jolla voidaan luoda eristettyjä Python ympäristöjä (lähde: Virtualenv, https://virtualenv.pypa.io/en/stable/).

Asennus tehtiin komennolla `sudo apt-get -y install virtualenv`. Seuraavaksi ajoin komennon `virtualenv --system-site-packages -p python3 env/`, joka luo kansion **/env**. Kansion kautta voidaan käyttää paketteja virutaalisten ympäristöjen ulkopuolellakin, sillä Pythonin paketteja voi asentaa myös komennolla apt-get komennolla. (lähde: Tero Karvinen, https://terokarvinen.com/2022/django-instant-crm-tutorial/)

Kävin kurkkaamassa, mihin kansio sijoittautui ja mitä se piti sisällään. Ilmeisesti ohjeessa mainittu lib/site-packages/ -kansio muodostuu myöhemmin, sillä sitä en listauksesta löytänyt.

![image](https://github.com/user-attachments/assets/2ec378f0-aae3-47ad-8100-79df5edfb468)

Seuraavaksi käytin uutta virtuaalista ympäristöä komennolla `source env/bin/activate`. Komento ei ensiyrittämällä onnistunut, sillä olin env/ kansion sisässä, mutta kotikansiossa ollessani komento antoi Teron ohjeen mukaisen (env) -alun terminaaliin. 

![image](https://github.com/user-attachments/assets/c0448de6-7c6a-4648-861b-abd1dfc71d79)

Seuraavaksi tarkistin, että olin varmasti virtuaaliympäristön sisällä, komennolla `which pip`.

![image](https://github.com/user-attachments/assets/19f056b6-562b-4361-b324-c83b03578bf5)

Tarkistuksen jälkeen asensin micron, joka olikin jo asennettuna virtuaalipalvelimeen, eli näemmä myös virtuaaliympäristöön. Sen jälkeen loin microlla uuden tekstitiedoston nimeltä requirements.txt, johon kirjoitin sisään **django**. Tallensin tiedoston painamalla Ctrl+S, ja poistun editorista painamalla Ctrl+Q. Tulostin terminaaliin vielä tiedoston sisällön, Teron ohjeen mukaisesti.

![image](https://github.com/user-attachments/assets/063f60d9-e2e1-46f9-b6a7-21e5e68b2273)

Seuraavaksi asensin Djangon, ja tarkistin asennnuksen jälkeen, mikä versio Djangosta on käytössä. (Yhden typon kautta, kuinkas muutenkaan...)

![image](https://github.com/user-attachments/assets/fce68683-ec33-403b-97e2-e060cc7ddc1e)

> Klo 19:17, tuotantoympäristö asennettuna, kahvinkeittotauko

> Klo 19:40, projektin luonnin aloitus

Teron ohjeen mukaan loin uuden projektin komennolla `django-admin startproject erikako`, ja lähdin kokeilemaan sitä. Ohjeesta poiketen sain virheilmoituksen, jonka mukaan minulla on 18 "unapplied migrations". Googlettelun jälkeen löysin Mediumin artikkelin aiheesta, jossa otettiin kantaa virheiden käsittelyyn (lähde: Taylor Berukoff, https://medium.com/@taylorberukoff/your-essential-django-setup-checklist-from-virtualenv-to-runserver-2fd8896e560c), mutta Teron ohjetta selatessani eteenpäin huomasin, että myös siellä otetaan kantaa näihin virheisiin vähän samalla tavalla kuin Mediumin artikkelissa, joten päätin tässä vaiheessa jättää virheet huomiotta.

![image](https://github.com/user-attachments/assets/cf9e3bcf-ac23-42df-a35f-b1171f51b441)

Testasin vielä selaimessa, että IP-osoite toimii, ja sain virheilmoituksen "Unable to connect".

![image](https://github.com/user-attachments/assets/4ed1ad84-f1e1-4825-81e8-3c6bc12dd718)

Kokeilin, toimisiko sivu jos lopetan käynnistetyn serverin terminaalissa komennolla Ctrl+C, ja käynnistän sen uudestaan, mutta sama lopputulos, eli samat herjat terminaalissa, eikä nettiselain näytä sivustoa. Nopean googlettelun tuloksena löysin keskustelun samaisesta ongelmasta, ja siellä oli vastattu, että onhan palvelimen palomuurissa reikä portille 8000 (lähde: Django, https://forum.djangoproject.com/t/cant-access-django-server-from-browser/22216). Tätä epäilin itsekin, ja halusin tietää, mitkä portit aiemmin olin aiemmin aukaissut. Etsin netistä tietoa, miten saan tietooni helposti ne portit, jotka on auki, mutta muutamia eri artikkeleita selatessani en löytänyt mielestäni tarpeeksi yksinkertaista ja nopeaa tapaa selvittää asiaa. Luotin siis omiin muistiinpanoihini, ja kävin tarkistamassa tehtävän h4 (https://github.com/koskinene/linux-course/blob/main/h4.md), mitkä portit olin avannut virtuaalipalvelimelle.

Avasin uuden terminaalin, jossa otin uuden yhteyden virtuaalipalvelimelle. Tässä kohtaa etsin tietoa, meneekö portin 8000 avaaminen samalla tavalla kuin porttien 80 ja 22 avaukset, ja löysinkin StackOverflown keskustelun (lähde: https://stackoverflow.com/questions/61561295/port-8000-not-enable-even-after-enable-it-on-firewall-ubuntu-18), jossa oli kerrottu suhteellisen yksinkertainen tapa listata avoinna olevat portit komennolla `sudo ufw status`, joten ajoin vielä sen varmistaakseni portit.

![image](https://github.com/user-attachments/assets/e6daad7a-a9b9-43b0-8f64-78e613c7c7e5)

Avasin palomuuriin reiän portilla 8000 komennolla `sudo ufw allow 8000/tcp`, ja tarkistin, että tulihan portti avoinna olevien listaukseen.

![image](https://github.com/user-attachments/assets/4c3d2be8-f157-499d-89cd-ff683e1b33ed)

Poistuin virtuaalikoneelta toisessa terminaalissa komennolla "exit", ja suljin terminaali-ikkunan. Jatkoin toisessa terminaali-ikkunassa, jossa ensin lopetin serverin pyörimisen komennolla Ctrl+C, ja käynnistin sen taas uudestaan. Vieläkään ei selaimessa näkynyt muuta kuin sama virheilmoitus, ja ajattelin kokeilla poistumista virtuaaliympäristöstä kokonaan, ja kokeilemalla uudestaan alusta.

Löysin StackOverflown keskustelun (lähde: StackOverflow, https://stackoverflow.com/questions/990754/how-to-leave-exit-deactivate-a-python-virtualenv), jossa kerrottiin kuinka virtuaaliympäristöstä pääsee pois, ja ajoin komennon `deactivate`, ja ainakin (env) -alku poistui terminaalista. Poistuin virtuaalipalvelimelta komennolla "exit", ja suljin varuilta vielä koko terminaali-ikkunankin.

> Klo 20:20, uusi yritys

Avasin uuden yhteyden virtuaalipalvelimelle, aktivoin uudelleen yhteyden virtuaaliympäristöön ja siirryin oikeaan projektikansioon. 

![image](https://github.com/user-attachments/assets/859615bd-a7ff-4df8-a06c-b95c949146e3)

Ajoin komennon `./manage.py runserver`, samat virheilmoitukset terminaalissa, eikä selaimessa edelleenkään näy muuta kuin virheilmoitus.

Googlettelulla en löytänyt oikein mitään järkevää, joten kysyin ChatGPT:ltä apua.

![image](https://github.com/user-attachments/assets/a6514ec8-3dbd-461b-8729-5cbda430bc38)

![image](https://github.com/user-attachments/assets/6f3beec7-3b35-4d10-bf2d-76b00b2bdf8e)

Lähdin kokeilemaan näillä ohjeilla, joten ensin stoppasin serverin painamalla Ctlr+C. Seuraavaksi käynnistin sen komennolla `./manage.py runserver 0.0.0.0:8000`. 2. kohdan olin juuri äsken tehnyt, eli reikä palomuuriin porttia varten. 3. kohdan skippasin, koska tiedän serverini IP-osoitteen, joten kokeilin suoraan kohtaa 4.

![image](https://github.com/user-attachments/assets/43442c9d-15cb-46dc-854a-ce2bd2eafb4c)

Aloin epäilemään, pitikö tehtävä tehdä edes virtuaalipalvelimen puolella, sillä tietysti nettiselain on virtuaalikoneen puolella, kun taas djangon asennukset yms. on tehty virtuaaliserverille, eikä siksi tietysti IP-osoite toimikaan virtuaalikoneen puolella. Tehtävänannossa sanotaan että voi halutessaan käyttää "testipalvelinta", ja seuraava tehtäväkin ohjeistetaan tekemään virtuaalikoneen puolella.

Aloitetaan siis alusta. Stoppasin serverin virtuaalipalvelimen puolella, ja vaihdoin terminaalissa takaisin oman virtuaalikoneeni puolelle. 

> Klo 20:55, uudestaan aloitus pienen hengitystauon jälkeen

Asensin tuotantoympäristön komennolla `sudo apt-get -y install virtualenv`, loin env/ -kansion komennolla `virtualenv --system-site-packages -p python3 env/` ja aktivoin virtuaaliympäristön komennolla `source env/bin/activate`. 

Etenin Teron ohjeen mukaisesti komennoilla, ja tässä kohtaa kaikki meni kuten aiemminkin virtuaaliserverin puolella.

![image](https://github.com/user-attachments/assets/cd8a6b9c-e034-4f31-9e87-c352daab1873)

Seuraavaksi loin projektin samaan tapaan kuin aiemminkin, komennolla `django-admin startproject erikako`, siirryin kansioon komennolla `cd erikako`, ja ajoin siellä komennon `./manage.py runserver`. Samat herjat terminaalissa unapplied migrations, mutta viimein selain toimii!

![image](https://github.com/user-attachments/assets/435a8604-2a4e-4870-87bf-cb8a92ad60eb)

Käyttöönotto oli huomattavasti nopeampaa näin toisen kerran tehtynä... 

Seuraavaksi jatkoin ohjeen mukaan adminin käyttöliittymän luontiin. Nettiselain näytti ihan oikein kirjautumisikkunaa, ja terminaalissa tapahtui lokitusta.

![image](https://github.com/user-attachments/assets/a88e7d20-4585-4d00-ae01-80fd0c84eb93)

Serveri oli stopattava, jotta pääsin kirjoittamaan komentoja joilla päivitetään tietokannat sekä luodaan käyttäjä.

Tietokannat päivitettiin Teron ohjeen mukaan komennoilla `./manage.py makemigrations` ja `./manage.py migrate`.

![image](https://github.com/user-attachments/assets/faaf647e-5636-4240-bebe-774ebd158091)

Lisäsin käyttäjän ohjeen mukaisilla komennoilla, ensin asensin pwgenin komennolla `sudo apt-get install pwgen`. Pwgen siis generoi salasanoja, ja käytin sitä salasanan luontiin komennolla `pwgen -s 20 1`. Otin salasanan talteen, ja loin "superuserin" komennolla `./manage.py createsuperuser`. Jätin käyttäjänimen tyhjäksi, jolloin se on erikak, en syöttänyt sähköpostia ja laitoin salasanan kahteen kertaan.

Kokeilin kirjautumista selaimessa, mutta eihän se toiminut koska serveri ei ollut päällä. Käynnistin sen uudestaan terminaalissa käyttäen komentoa `./manage.py runserver`.

Nyt terminaalissa ei näkynyt enää varoituksia, ja pääsin selaimen kautta kirjautumaan.

![image](https://github.com/user-attachments/assets/a996da31-06ca-4e36-8030-fdca1e69fd6c)

Ohjeessa jää epäselväksi, pitääkö uusi käyttäjä luoda terminaalin vai nettiselaimen kautta, mutta päätin ensin kokeilla käyttäjän luontia nettiselaimen kautta. Tämä tehtiin valitsemalla vasemman reunan Users -kohdasta "Add", ja lisäämällä käyttäjälle käyttäjänimi sekä salasana. Painoin alareunasta "Save and continue editing", jotta pääsisin lisäämään käyttöoikeuksia käyttäjälle. Alempana sivulta löytyi kohta "Permissions", jossa rastin kohdat "Staff status" sekä "Superuser status". 

![image](https://github.com/user-attachments/assets/e00e260f-d800-4523-9fe0-a99b4a490177)

En tehnyt käyttäjään muita muutoksia, ja tallensin tehdyt muutokset alareunan "SAVE"-nappia painamalla, jolloin sivu kertoi "The user "testailu" was changed successfully", eli kaikki OK. Seuraavaksi kirjauduin ulos, ja kirjauduin sisään juuri luomallani käyttäjällä ja kaikki näyttäisi toimivan kuten pitääkin.

![image](https://github.com/user-attachments/assets/4768a98a-d1e1-414c-8545-b5cfc9ce34c3)

Testasin vielä testailu-käyttäjän oikeudet luomalla yhden uuden käyttäjän, jolle en laittanut mitään oikeuksia. Käyttäjän luominen onnistui ongelmitta, eli oikeudet juuri luodulle testailu-käyttäjälle olivat kunnossa. Users -listaa katsomalla näin, että myös Staff -statuksen kohdalla on vihreä merkintä testailu-tunnuksen kohdalla, eli myös se oikeus oli kunnossa.

> Klo 21:28, asiakastietokannan luonnin aloitus

Aloitin tietokannan luonnin Teron ohjeen mukaan komennolla `./manage.py startapp crm`, joka luo uuden kansion Customer Relationship Management (CRM) -sovellukselle (lähde: Tero Karvinen, https://terokarvinen.com/2022/django-instant-crm-tutorial/). Lisäsin microlla crm -sovelluksen settins.py -tiedostoon kohtaan INSTALLED_APPS, tallensin painamalla Ctrl+S ja poistuin microsta painamalla Ctrl+Q.

Seuraavaksi ohjeen mukaisesti lisäsin mallin komennolla `micro crm/models.py`. Customer -luokka lisää näillä määrityksillä customer -taulun tietokantaan, ja lisää tauluun name -sarakkeen. Taas tallennus Ctlr+S ja poistuminen Ctrl+Q.

![image](https://github.com/user-attachments/assets/adf547a3-ec70-4109-9b78-7dbaf7cf5306)

Seuraavaksi ajoin komennot migraatioita varten, eli otin äsken tehdyn mallin "käyttöön".

![image](https://github.com/user-attachments/assets/396c9fed-8511-4f77-8967-83b851d0adbf)

Rekisteröin ohjeen mukaisesti juuri luodun tietokannan näkymään adminille muokkaamalla microlla tiedostoa admin.py. Ctrl+S tallennukseen ja Ctrl+Q poistumiseen. 

![image](https://github.com/user-attachments/assets/9a77a08c-e5e0-4dd7-8009-ca72ff471369)

Laitoin serverin käyntiin komennolla `./manage.py runserver`, ja kirjauduin admin-näkymästä sisään. Juuri luotu Customers -tietokanta näkyi. Testasin tietokannan toimintaa lisäämällä kaksi käyttäjää, poistamalla yhden, lisäämällä yhden ja muokkaamalla toista. Kaikki toiminnot toimivat normaalisti.

![image](https://github.com/user-attachments/assets/c56f886c-8aab-495f-a4fd-b78c02ff0df9)






























































