# Hello Django

## 27.9.2024

## a) Esimerkkiohjelma Djangolla

> Klo 18:52, tuotantoympäristön asennuksen aloitus

Aloitin tehtävien teon käynnistämällä virtuaalikoneeni ja ajamalla siellä terminaalissa tutun komennon `sudo apt-get update`. Päivitysten jälkeen otin yhteyden virtuaalipalvelimeeni komennolla `ssh erikak@165.232.86.216`, ja ajoin myös siellä päivityskomennon.

Lähdin etenemään Tero Karvisen ohjeen mukaan (lähde: Tero Karvinen, https://terokarvinen.com/2022/django-instant-crm-tutorial/), ja ensimmäisenä asensin virtuaalipalvelimelleni virtualenvin, joka on siis työkalu jolla voidaan luoda eristettyjä Python ympäristöjä (lähde: Virtualenv, https://virtualenv.pypa.io/en/stable/).

Asennus tehtiin komennolla `sudo apt-get -y install virtualenv`. Seuraavaksi ajoin komennon `virtualenv --system-site-packages -p python3 env/`, joka luo kansion **/env**. Kansion kautta voidaan käyttää paketteja virutaalisten ympäristöjen ulkopuolellakin, sillä Pythonin paketteja voi asentaa myös komennolla apt-get komennolla. (lähde: Tero Karvinen, https://terokarvinen.com/2022/django-instant-crm-tutorial/)

Kävin kurkkaamassa, mihin kansio sijoittautui ja mitä se piti sisällään. Ilmeisesti ohjeessa mainittu lib/site-packages/ -kansio muodostuu myöhemmin, sillä sitä en listauksesta löytänyt.

![image](https://github.com/user-attachments/assets/2ec378f0-aae3-47ad-8100-79df5edfb468)

Seuraavaksi käytin uutta virtuaalista ympäristöä komennolla `source env/bin/activate`. Komento ei ensiyrittämällä onnistunut, sillä olin env/ kansion sisässä, mutta kotikansiossa ollessani komento antoi Teron ohjeen mukaisen (env) -alun terminaaliin. 

![image](https://github.com/user-attachments/assets/c0448de6-7c6a-4648-861b-abd1dfc71d79)

Seuraavaksi tarkistin, että olin varmasti virtuaaliympäristön sisällä, komennolla `which pip`.

![image](https://github.com/user-attachments/assets/19f056b6-562b-4361-b324-c83b03578bf5)

Tarkistuksen jälkeen asensin micron, joka olikin jo asennettuna virtuaalipalvelimeen, eli näemmä myös virtuaaliympäristöön. Sen jälkeen loin microlla uuden tekstitiedoston nimeltä requirements.txt, johon kirjoitin sisään **django**. Tallensin tiedoston painamalla Ctrl+S, ja poistun editorista painamalla Ctrl+Q. Tulostin terminaaliin vielä tiedoston sisällön, Teron ohjeen mukaisesti.

![image](https://github.com/user-attachments/assets/063f60d9-e2e1-46f9-b6a7-21e5e68b2273)

Seuraavaksi asensin Djangon, ja tarkistin asennnuksen jälkeen, mikä versio Djangosta on käytössä. (Yhden typon kautta, kuinkas muutenkaan...)

![image](https://github.com/user-attachments/assets/fce68683-ec33-403b-97e2-e060cc7ddc1e)

> Klo 19:17, tuotantoympäristö asennettuna, kahvinkeittotauko

> Klo 19:40, projektin luonnin aloitus

Teron ohjeen mukaan loin uuden projektin komennolla `django-admin startproject erikako`, ja lähdin kokeilemaan sitä. Ohjeesta poiketen sain virheilmoituksen, jonka mukaan minulla on 18 "unapplied migrations". Googlettelun jälkeen löysin Mediumin artikkelin aiheesta, jossa otettiin kantaa virheiden käsittelyyn (lähde: Taylor Berukoff, https://medium.com/@taylorberukoff/your-essential-django-setup-checklist-from-virtualenv-to-runserver-2fd8896e560c), mutta Teron ohjetta selatessani eteenpäin huomasin, että myös siellä otetaan kantaa näihin virheisiin vähän samalla tavalla kuin Mediumin artikkelissa, joten päätin tässä vaiheessa jättää virheet huomiotta.

![image](https://github.com/user-attachments/assets/cf9e3bcf-ac23-42df-a35f-b1171f51b441)

Testasin vielä selaimessa, että IP-osoite toimii, ja sain virheilmoituksen "Unable to connect".

![image](https://github.com/user-attachments/assets/4ed1ad84-f1e1-4825-81e8-3c6bc12dd718)

Kokeilin, toimisiko sivu jos lopetan käynnistetyn serverin terminaalissa komennolla Ctrl+C, ja käynnistän sen uudestaan, mutta sama lopputulos, eli samat herjat terminaalissa, eikä nettiselain näytä sivustoa. Nopean googlettelun tuloksena löysin keskustelun samaisesta ongelmasta, ja siellä oli vastattu, että onhan palvelimen palomuurissa reikä portille 8000 (lähde: Django, https://forum.djangoproject.com/t/cant-access-django-server-from-browser/22216). Tätä epäilin itsekin, ja halusin tietää, mitkä portit aiemmin olin aiemmin aukaissut. Etsin netistä tietoa, miten saan tietooni helposti ne portit, jotka on auki, mutta muutamia eri artikkeleita selatessani en löytänyt mielestäni tarpeeksi yksinkertaista ja nopeaa tapaa selvittää asiaa. Luotin siis omiin muistiinpanoihini, ja kävin tarkistamassa tehtävän h4 (https://github.com/koskinene/linux-course/blob/main/h4.md), mitkä portit olin avannut virtuaalipalvelimelle.

Avasin uuden terminaalin, jossa otin uuden yhteyden virtuaalipalvelimelle. Tässä kohtaa etsin tietoa, meneekö portin 8000 avaaminen samalla tavalla kuin porttien 80 ja 22 avaukset, ja löysinkin StackOverflown keskustelun (lähde: https://stackoverflow.com/questions/61561295/port-8000-not-enable-even-after-enable-it-on-firewall-ubuntu-18), jossa oli kerrottu suhteellisen yksinkertainen tapa listata avoinna olevat portit komennolla `sudo ufw status`, joten ajoin vielä sen varmistaakseni portit.

![image](https://github.com/user-attachments/assets/e6daad7a-a9b9-43b0-8f64-78e613c7c7e5)

Avasin palomuuriin reiän portilla 8000 komennolla `sudo ufw allow 8000/tcp`, ja tarkistin, että tulihan portti avoinna olevien listaukseen.

![image](https://github.com/user-attachments/assets/4c3d2be8-f157-499d-89cd-ff683e1b33ed)

Poistuin virtuaalikoneelta toisessa terminaalissa komennolla "exit", ja suljin terminaali-ikkunan. Jatkoin toisessa terminaali-ikkunassa, jossa ensin lopetin serverin pyörimisen komennolla Ctrl+C, ja käynnistin sen taas uudestaan. Vieläkään ei selaimessa näkynyt muuta kuin sama virheilmoitus, ja ajattelin kokeilla poistumista virtuaaliympäristöstä kokonaan, ja kokeilemalla uudestaan alusta.

Löysin StackOverflown keskustelun (lähde: StackOverflow, https://stackoverflow.com/questions/990754/how-to-leave-exit-deactivate-a-python-virtualenv), jossa kerrottiin kuinka virtuaaliympäristöstä pääsee pois, ja ajoin komennon `deactivate`, ja ainakin (env) -alku poistui terminaalista. Poistuin virtuaalipalvelimelta komennolla "exit", ja suljin varuilta vielä koko terminaali-ikkunankin.

> Klo 20:20, uusi yritys

Avasin uuden yhteyden virtuaalipalvelimelle, aktivoin uudelleen yhteyden virtuaaliympäristöön ja siirryin oikeaan projektikansioon. 

![image](https://github.com/user-attachments/assets/859615bd-a7ff-4df8-a06c-b95c949146e3)

Ajoin komennon `./manage.py runserver`, samat virheilmoitukset terminaalissa, eikä selaimessa edelleenkään näy muuta kuin virheilmoitus.

Googlettelulla en löytänyt oikein mitään järkevää, joten kysyin ChatGPT:ltä apua.

![image](https://github.com/user-attachments/assets/23cfa878-2e22-475d-9327-364964c137fd)









































